### ISSUE TITLE
Add "How does this play with React"?

### ISSUE THREAD

**Issue by Carreau** [phosphorjs/phosphorjs.github.io#10]
And what about react. 
In the description docs. 

Discussed on weekly meeting, just make an issue to track.

**Comment by fperez** [comment]
I wouldn't quite say 'why not react', rather how it complements/plays with a react ecosystem.

**Comment by Carreau** [comment]
Also what the relation Jupyter/Phosphor in a FAQ somewhere , maybe on Jupyter-side.

**Comment by sccolbert** [comment]
To what extent do we want to call out React directly, versus the language which _already_ states that Phosphor plays nicely with any other framework:

> PhosphorJS was designed from the start to play nicely with existing and popular web frameworks

Explicit examples are one thing (which will come), I'm talking about the overview language specifically.

**Comment by fperez** [comment]
I don't know, I've had the question about phosphor/react asked directly multiple times, so I think it's best to address it explicitly... If that's the question in people's minds, the more directly and unambiguously the information on the page answers it, I think the more easily the project will find a space in the ecosystem... At least that's how I see it.

But keep in mind, I'm a _rank newbie_ at this game, I don't actually write any of this code. It's just that people do ask me about this topic, because we're using the tools in the project, but in this particular case, I'm not the one really working on the code... So I'm taking the real raw beginner view of the problem (which I think can actually be valuable as well).

**Comment by sccolbert** [comment]
Fixed in #16

**Comment by fperez** [comment]
Thanks so much, I think this will help a lot in answering a very common question.
